name: CD Pipeline

on:
  push:
    branches:
      - "main"
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew

      - name: Build project
        run: ./gradlew build

      - name: Publish to GitHub Packages
        run: ./gradlew publish

        env:
          GITHUB_ACTOR: ${{ env.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.JAVA_TOKEN }}

