name: CI

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v2
      - name: Build with Gradle Wrapper
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

      - name: Run coverage with Kover
        run: ./gradlew koverReport

      - name: Run linting
        run: ./gradlew ktlintCheck

      - name: Check formatter
        run: ./gradlew checkFormatter

      # No ejecutar el formatter
